# Generated by Django 4.2.4 on 2023-09-04 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="birth_date",),
    ]
